Toba/urls.py
from django.urls import path
from . import views

app_name = "toba"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:place_id>", views.detail, name="detail")
]

TobaExPy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Toba.urls"))
]

Toba/models.py
from django.db import models


# ジャンル
class Type(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# places model
class Place(models.Model):
    place_id = models.CharField(max_length=100, primary_key=True)
    lat = models.DecimalField(max_digits=9, decimal_places=6)  # 経度
    lng = models.DecimalField(max_digits=9, decimal_places=6)  # 緯度
    name = models.CharField(max_length=100)  # 施設の名前
    photo = models.CharField(max_length=1000, null=True)  # photo_reference
    vicinity = models.CharField(max_length=1000, null=True)  # 住所
    rating = models.FloatField(null=True)
    type = models.ManyToManyField(Type, blank=True)  # ジャンル

    def __str__(self):
        return self.name

Toba/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.template.context_processors import csrf
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from .models import Place
from .registers import register_places


def index(request):
    places = Place.objects.all()
    if len(places) == 0:
        register_places()
    return render(request, "toba/index.html", {
        "places": places
    })


def detail(request, place_id):
    place = Place.objects.get(place_id=place_id)
    return render(request, "toba/detail.html", {
        "toba": {"lat": 34.4868, "lng": 136.8431},
        "place": place,
        "place_types": [i_type for i_type in place.type.all()]
    })

templates/toba/base.html
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="UTF-8">

    {% load static %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %}創造実験{% endblock %}</title>
    <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">
    {% block head %}
    {% endblock %}
</head>
<body>

<!--メインコンテンツ-->
{% block content %}
{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/toba/detail.html
{% extends 'toba/base.html' %}
{% load staticfiles %}

{% block title %}{{ place.name }}{% endblock %}


{% block head %}
    <style>
        #map {
            height: 100%;
        }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB5W0x1aKzeLeeX2KeFeDk09WnJ53xFQQg"></script>
    <link rel="stylesheet" href="print.css" media="print">
{% endblock %}

{% block content %}
    <!-- map -->
    <div id="map"></div>

    <div>
        <ul>
            <li>place_id: {{ place.place_id }}</li>
            <li>lat: {{ place.lat }}</li>
            <li>lng: {{ place.lng }}</li>
            <li>name: {{ place.name }}</li>
            <li>photo: {{ place.photo }}</li>
            <li>vicinity: {{ place.vicinity }}</li>
            <li>rating: {{ place.rating }}</li>
            {% for i_type in place_types %}
                <li>type: {{ i_type }}</li>
            {% endfor %}
        </ul>
        <button onclick="printAnyMaps()">印刷</button>
    </div>



    <script>
        let map;
        let toba_lat = {{ toba.lat }};
        let toba_lng = {{ toba.lng }};
        let place_lat = {{ place.lat }};
        let place_lng = {{ place.lng }};

        function initialize() {
            let options = {
                zoom: 16,
                center: new google.maps.LatLng(toba_lat, toba_lng),
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            map = new google.maps.Map(document.getElementById('map'), options);

            let rendererOptions = {
                map: map, // 描画先の地図
                draggable: true, // ドラッグ可
                preserveViewport: true // centerの座標、ズームレベルで表示
            };
            let directionsDisplay = new google.maps.DirectionsRenderer(rendererOptions);
            let directionsService = new google.maps.DirectionsService();
            directionsDisplay.setMap(map);
            let request = {
                origin: new google.maps.LatLng(toba_lat, toba_lng), // スタート地点
                destination: new google.maps.LatLng(place_lat, place_lng), // ゴール地点
                travelMode: google.maps.DirectionsTravelMode.WALKING, // 移動手段
            };
            directionsService.route(request, function (response, status) {
                if (status === google.maps.DirectionsStatus.OK) {
                    new google.maps.DirectionsRenderer({
                        map: map,
                        directions: response,
                        suppressMarkers: true // デフォルトのマーカーを削除
                    });
                    let leg = response.routes[0].legs[0];
                    makeMarker(leg.end_location, markers.goalMarker, map);
                    setTimeout(function () {
                        map.setZoom(16); // ルート表示後にズーム率を変更
                    });
                }
            })
        }

        initialize()
    </script>

    <!-- 印刷関数 -->
    <script>
        function printAnyMaps() {
            const $body = $('body');
            const $mapContainer = $('#map');
            const $mapContainerParent = $mapContainer.parent();
            const $printContainer = $('<div style="position:relative;">');

            $printContainer
                .height($mapContainer.height())
                .append($mapContainer)
                .prependTo($body);

            const $content = $body
                .children()
                .not($printContainer)
                .not('script')
                .detach();

            /**
             * Needed for those who use Bootstrap 3.x, because some of
             * its `@media print` styles ain't play nicely when printing.
             */
            const $patchedStyle = $('<style media="print">')
                .text(`
      img { max-width: none !important; }
      a[href]:after { content: ""; }
    `)
                .appendTo('head');

            window.print();

            $body.prepend($content);
            $mapContainerParent.prepend($mapContainer);

            $printContainer.remove();
            $patchedStyle.remove();
        }
    </script>
{% endblock %}

templates/toba/index.html
{% extends 'toba/base.html' %}
{% load staticfiles %}

{% block title %}鳥羽観光案内トップ{% endblock %}

{% block content %}

    {% for place in places %}
        <ul>
            <li><a href={% url "toba:detail" place_id=place.place_id %}>{{ place.name }}</a></li>
        </ul>
    {% endfor %}

{% endblock %}